//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MusicSchool
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Group.
    /// </summary>
    //  *** Start programmer edit section *** (Group CustomAttributes)

    //  *** End programmer edit section *** (Group CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("GroupE", new string[] {
            "Name as \'Name\'",
            "PupilCount as \'Pupil count\'"})]
    [AssociatedDetailViewAttribute("GroupE", "PupilInGroup", "PupilInGroupE", true, "", "Pupil in group", true, new string[] {
            ""})]
    [View("GroupL", new string[] {
            "Name as \'Name\'",
            "PupilCount as \'Pupil count\'"})]
    public class Group : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fPupilCount;
        
        private IIS.MusicSchool.DetailArrayOfPupilInGroup fPupilInGroup;
        
        //  *** Start programmer edit section *** (Group CustomMembers)

        //  *** End programmer edit section *** (Group CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Group.Name CustomAttributes)

        //  *** End programmer edit section *** (Group.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Group.Name Get start)

                //  *** End programmer edit section *** (Group.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Group.Name Get end)

                //  *** End programmer edit section *** (Group.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Group.Name Set start)

                //  *** End programmer edit section *** (Group.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Group.Name Set end)

                //  *** End programmer edit section *** (Group.Name Set end)
            }
        }
        
        /// <summary>
        /// PupilCount.
        /// </summary>
        //  *** Start programmer edit section *** (Group.PupilCount CustomAttributes)

        //  *** End programmer edit section *** (Group.PupilCount CustomAttributes)
        public virtual int PupilCount
        {
            get
            {
                //  *** Start programmer edit section *** (Group.PupilCount Get start)

                //  *** End programmer edit section *** (Group.PupilCount Get start)
                int result = this.fPupilCount;
                //  *** Start programmer edit section *** (Group.PupilCount Get end)

                //  *** End programmer edit section *** (Group.PupilCount Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Group.PupilCount Set start)

                //  *** End programmer edit section *** (Group.PupilCount Set start)
                this.fPupilCount = value;
                //  *** Start programmer edit section *** (Group.PupilCount Set end)

                //  *** End programmer edit section *** (Group.PupilCount Set end)
            }
        }
        
        /// <summary>
        /// Group.
        /// </summary>
        //  *** Start programmer edit section *** (Group.PupilInGroup CustomAttributes)

        //  *** End programmer edit section *** (Group.PupilInGroup CustomAttributes)
        public virtual IIS.MusicSchool.DetailArrayOfPupilInGroup PupilInGroup
        {
            get
            {
                //  *** Start programmer edit section *** (Group.PupilInGroup Get start)

                //  *** End programmer edit section *** (Group.PupilInGroup Get start)
                if ((this.fPupilInGroup == null))
                {
                    this.fPupilInGroup = new IIS.MusicSchool.DetailArrayOfPupilInGroup(this);
                }
                IIS.MusicSchool.DetailArrayOfPupilInGroup result = this.fPupilInGroup;
                //  *** Start programmer edit section *** (Group.PupilInGroup Get end)

                //  *** End programmer edit section *** (Group.PupilInGroup Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Group.PupilInGroup Set start)

                //  *** End programmer edit section *** (Group.PupilInGroup Set start)
                this.fPupilInGroup = value;
                //  *** Start programmer edit section *** (Group.PupilInGroup Set end)

                //  *** End programmer edit section *** (Group.PupilInGroup Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "GroupE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GroupE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GroupE", typeof(IIS.MusicSchool.Group));
                }
            }
            
            /// <summary>
            /// "GroupL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GroupL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GroupL", typeof(IIS.MusicSchool.Group));
                }
            }
        }
    }
}
