//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MusicSchool
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Lesson.
    /// </summary>
    //  *** Start programmer edit section *** (Lesson CustomAttributes)

    //  *** End programmer edit section *** (Lesson CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LessonE", new string[] {
            "Mark as \'Mark\'",
            "Date as \'Date\'",
            "Comment as \'Comment\'",
            "Teacher as \'Teacher\'",
            "Teacher.Name as \'Name\'",
            "Pupil as \'Pupil\'",
            "Pupil.Name as \'Name\'"}, Hidden=new string[] {
            "Teacher.Name",
            "Pupil.Name"})]
    [MasterViewDefineAttribute("LessonE", "Teacher", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("LessonE", "Pupil", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("LessonL", new string[] {
            "Mark as \'Mark\'",
            "Date as \'Date\'",
            "Comment as \'Comment\'",
            "Teacher.Name as \'Name\'",
            "Pupil.Name as \'Name\'"})]
    public class Lesson : ICSSoft.STORMNET.DataObject
    {
        
        private string fMark;
        
        private System.DateTime fDate;
        
        private string fComment;
        
        private IIS.MusicSchool.Teacher fTeacher;
        
        private IIS.MusicSchool.Pupil fPupil;
        
        //  *** Start programmer edit section *** (Lesson CustomMembers)

        //  *** End programmer edit section *** (Lesson CustomMembers)

        
        /// <summary>
        /// Mark.
        /// </summary>
        //  *** Start programmer edit section *** (Lesson.Mark CustomAttributes)

        //  *** End programmer edit section *** (Lesson.Mark CustomAttributes)
        [StrLen(255)]
        public virtual string Mark
        {
            get
            {
                //  *** Start programmer edit section *** (Lesson.Mark Get start)

                //  *** End programmer edit section *** (Lesson.Mark Get start)
                string result = this.fMark;
                //  *** Start programmer edit section *** (Lesson.Mark Get end)

                //  *** End programmer edit section *** (Lesson.Mark Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Lesson.Mark Set start)

                //  *** End programmer edit section *** (Lesson.Mark Set start)
                this.fMark = value;
                //  *** Start programmer edit section *** (Lesson.Mark Set end)

                //  *** End programmer edit section *** (Lesson.Mark Set end)
            }
        }
        
        /// <summary>
        /// Date.
        /// </summary>
        //  *** Start programmer edit section *** (Lesson.Date CustomAttributes)

        //  *** End programmer edit section *** (Lesson.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                //  *** Start programmer edit section *** (Lesson.Date Get start)

                //  *** End programmer edit section *** (Lesson.Date Get start)
                System.DateTime result = this.fDate;
                //  *** Start programmer edit section *** (Lesson.Date Get end)

                //  *** End programmer edit section *** (Lesson.Date Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Lesson.Date Set start)

                //  *** End programmer edit section *** (Lesson.Date Set start)
                this.fDate = value;
                //  *** Start programmer edit section *** (Lesson.Date Set end)

                //  *** End programmer edit section *** (Lesson.Date Set end)
            }
        }
        
        /// <summary>
        /// Comment.
        /// </summary>
        //  *** Start programmer edit section *** (Lesson.Comment CustomAttributes)

        //  *** End programmer edit section *** (Lesson.Comment CustomAttributes)
        [StrLen(255)]
        public virtual string Comment
        {
            get
            {
                //  *** Start programmer edit section *** (Lesson.Comment Get start)

                //  *** End programmer edit section *** (Lesson.Comment Get start)
                string result = this.fComment;
                //  *** Start programmer edit section *** (Lesson.Comment Get end)

                //  *** End programmer edit section *** (Lesson.Comment Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Lesson.Comment Set start)

                //  *** End programmer edit section *** (Lesson.Comment Set start)
                this.fComment = value;
                //  *** Start programmer edit section *** (Lesson.Comment Set end)

                //  *** End programmer edit section *** (Lesson.Comment Set end)
            }
        }
        
        /// <summary>
        /// Lesson.
        /// </summary>
        //  *** Start programmer edit section *** (Lesson.Teacher CustomAttributes)

        //  *** End programmer edit section *** (Lesson.Teacher CustomAttributes)
        [NotNull()]
        public virtual IIS.MusicSchool.Teacher Teacher
        {
            get
            {
                //  *** Start programmer edit section *** (Lesson.Teacher Get start)

                //  *** End programmer edit section *** (Lesson.Teacher Get start)
                IIS.MusicSchool.Teacher result = this.fTeacher;
                //  *** Start programmer edit section *** (Lesson.Teacher Get end)

                //  *** End programmer edit section *** (Lesson.Teacher Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Lesson.Teacher Set start)

                //  *** End programmer edit section *** (Lesson.Teacher Set start)
                this.fTeacher = value;
                //  *** Start programmer edit section *** (Lesson.Teacher Set end)

                //  *** End programmer edit section *** (Lesson.Teacher Set end)
            }
        }
        
        /// <summary>
        /// Lesson.
        /// </summary>
        //  *** Start programmer edit section *** (Lesson.Pupil CustomAttributes)

        //  *** End programmer edit section *** (Lesson.Pupil CustomAttributes)
        [NotNull()]
        public virtual IIS.MusicSchool.Pupil Pupil
        {
            get
            {
                //  *** Start programmer edit section *** (Lesson.Pupil Get start)

                //  *** End programmer edit section *** (Lesson.Pupil Get start)
                IIS.MusicSchool.Pupil result = this.fPupil;
                //  *** Start programmer edit section *** (Lesson.Pupil Get end)

                //  *** End programmer edit section *** (Lesson.Pupil Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Lesson.Pupil Set start)

                //  *** End programmer edit section *** (Lesson.Pupil Set start)
                this.fPupil = value;
                //  *** Start programmer edit section *** (Lesson.Pupil Set end)

                //  *** End programmer edit section *** (Lesson.Pupil Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LessonE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LessonE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LessonE", typeof(IIS.MusicSchool.Lesson));
                }
            }
            
            /// <summary>
            /// "LessonL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LessonL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LessonL", typeof(IIS.MusicSchool.Lesson));
                }
            }
        }
    }
}
