//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MusicSchool
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Pupil in group.
    /// </summary>
    //  *** Start programmer edit section *** (PupilInGroup CustomAttributes)

    //  *** End programmer edit section *** (PupilInGroup CustomAttributes)
    [AutoAltered()]
    [Caption("Pupil in group")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PupilInGroupE", new string[] {
            "Active as \'Active\'",
            "Pupil as \'Pupil\'",
            "Pupil.Name as \'Name\'"}, Hidden=new string[] {
            "Pupil.Name"})]
    [MasterViewDefineAttribute("PupilInGroupE", "Pupil", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class PupilInGroup : ICSSoft.STORMNET.DataObject
    {
        
        private bool fActive = true;
        
        private IIS.MusicSchool.Pupil fPupil;
        
        private IIS.MusicSchool.Group fGroup;
        
        //  *** Start programmer edit section *** (PupilInGroup CustomMembers)

        //  *** End programmer edit section *** (PupilInGroup CustomMembers)

        
        /// <summary>
        /// Active.
        /// </summary>
        //  *** Start programmer edit section *** (PupilInGroup.Active CustomAttributes)

        //  *** End programmer edit section *** (PupilInGroup.Active CustomAttributes)
        public virtual bool Active
        {
            get
            {
                //  *** Start programmer edit section *** (PupilInGroup.Active Get start)

                //  *** End programmer edit section *** (PupilInGroup.Active Get start)
                bool result = this.fActive;
                //  *** Start programmer edit section *** (PupilInGroup.Active Get end)

                //  *** End programmer edit section *** (PupilInGroup.Active Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (PupilInGroup.Active Set start)

                //  *** End programmer edit section *** (PupilInGroup.Active Set start)
                this.fActive = value;
                //  *** Start programmer edit section *** (PupilInGroup.Active Set end)

                //  *** End programmer edit section *** (PupilInGroup.Active Set end)
            }
        }
        
        /// <summary>
        /// Pupil in group.
        /// </summary>
        //  *** Start programmer edit section *** (PupilInGroup.Pupil CustomAttributes)

        //  *** End programmer edit section *** (PupilInGroup.Pupil CustomAttributes)
        [NotNull()]
        public virtual IIS.MusicSchool.Pupil Pupil
        {
            get
            {
                //  *** Start programmer edit section *** (PupilInGroup.Pupil Get start)

                //  *** End programmer edit section *** (PupilInGroup.Pupil Get start)
                IIS.MusicSchool.Pupil result = this.fPupil;
                //  *** Start programmer edit section *** (PupilInGroup.Pupil Get end)

                //  *** End programmer edit section *** (PupilInGroup.Pupil Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (PupilInGroup.Pupil Set start)

                //  *** End programmer edit section *** (PupilInGroup.Pupil Set start)
                this.fPupil = value;
                //  *** Start programmer edit section *** (PupilInGroup.Pupil Set end)

                //  *** End programmer edit section *** (PupilInGroup.Pupil Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.MusicSchool.Group.
        /// </summary>
        //  *** Start programmer edit section *** (PupilInGroup.Group CustomAttributes)

        //  *** End programmer edit section *** (PupilInGroup.Group CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.MusicSchool.Group Group
        {
            get
            {
                //  *** Start programmer edit section *** (PupilInGroup.Group Get start)

                //  *** End programmer edit section *** (PupilInGroup.Group Get start)
                IIS.MusicSchool.Group result = this.fGroup;
                //  *** Start programmer edit section *** (PupilInGroup.Group Get end)

                //  *** End programmer edit section *** (PupilInGroup.Group Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (PupilInGroup.Group Set start)

                //  *** End programmer edit section *** (PupilInGroup.Group Set start)
                this.fGroup = value;
                //  *** Start programmer edit section *** (PupilInGroup.Group Set end)

                //  *** End programmer edit section *** (PupilInGroup.Group Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PupilInGroupE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PupilInGroupE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PupilInGroupE", typeof(IIS.MusicSchool.PupilInGroup));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of PupilInGroup.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfPupilInGroup CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfPupilInGroup CustomAttributes)
    public class DetailArrayOfPupilInGroup : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.MusicSchool.DetailArrayOfPupilInGroup members)

        //  *** End programmer edit section *** (IIS.MusicSchool.DetailArrayOfPupilInGroup members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type PupilInGroup by index.
        /// </summary>
        /// <summary>
        /// Adds object with type PupilInGroup.
        /// </summary>
        public DetailArrayOfPupilInGroup(IIS.MusicSchool.Group fGroup) : 
                base(typeof(PupilInGroup), ((ICSSoft.STORMNET.DataObject)(fGroup)))
        {
        }
        
        public IIS.MusicSchool.PupilInGroup this[int index]
        {
            get
            {
                return ((IIS.MusicSchool.PupilInGroup)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.MusicSchool.PupilInGroup dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
