//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MusicSchool
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Teacher.
    /// </summary>
    //  *** Start programmer edit section *** (Teacher CustomAttributes)

    //  *** End programmer edit section *** (Teacher CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TeacherE", new string[] {
            "Name as \'Name\'"})]
    [View("TeacherL", new string[] {
            "Name as \'Name\'"})]
    public class Teacher : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (Teacher CustomMembers)

        //  *** End programmer edit section *** (Teacher CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Teacher.Name CustomAttributes)

        //  *** End programmer edit section *** (Teacher.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Teacher.Name Get start)

                //  *** End programmer edit section *** (Teacher.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Teacher.Name Get end)

                //  *** End programmer edit section *** (Teacher.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Teacher.Name Set start)

                //  *** End programmer edit section *** (Teacher.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Teacher.Name Set end)

                //  *** End programmer edit section *** (Teacher.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TeacherE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherE", typeof(IIS.MusicSchool.Teacher));
                }
            }
            
            /// <summary>
            /// "TeacherL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherL", typeof(IIS.MusicSchool.Teacher));
                }
            }
        }
    }
}
